name: Publish to Scalar Docs

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Publish to Scalar
        run: npx @scalar/cli@latest project publish --token ${{ secrets.SCALAR_API_TOKEN }}
